### ISSUE TITLE
Was soll passieren, wenn der Hubschrauber zerstört wird?

### ISSUE THREAD

**Issue by Ugga-the-Caveman** [Ugga-the-Caveman/Support#11]
Hab einfach mal aus Spass den hubschrauber über feindlicher Flack abwerfen lassen. Hierbei konnte ich festellen, dass waypoints sofort completed sind, wenn das fahrzeug zerstört wird. XD

Der Support wird also auf jeden fall abgeworfen. Bug oder Feature? =)

**Comment by Blub0815** [comment]
Habe mir jetzt hier ein paar Gedanken gemacht. Und mir sind 2 Möglichkeiten eingefallen.
***
>Option 1: Wir machen den Heli unzerstörbar 
>oder
>Option 2: Der Startpunktbase
Allerdings bin ich erstmal für Option 1. Die erste Idee war es ein Script zur Verfügung zu stellen was noch nicht zu Kompliziert ist. Danach kann man immer noch sagen der spawnt in der Base. 
BZW War mein Gedanke ein 2tes Script zu erschaffen wo ein Heli in der Base spawnt.
***
Ich habe schon wieder mehrere Ideen die mir hier einfallen um ein 2tes Script zu erschaffen. Oder noch mehrere und dies als ein Set anzubieten xD omg

**Comment by Blub0815** [comment]
Oder noch besser. Wenn Heli zerstört dann sollte aber zumindest die Fracht nicht mehr abgeworfen werden

**Comment by Ugga-the-Caveman** [comment]
Heli einfach unzerstörbar machen ist die einfachste und sauberste Lösung. 
Gefällt mir wenig - _caller soll sich Gedanken über gegnerische Luftabwehr machen.
Ist schnell und einfach gemacht. 
Könnte man in der Dokumentation erwähnen. Ein Script-packet, aber anpassbar machen.

zu: Fracht nicht abwerfen, wenn heli vorher zerstört wird
Ja, find ich gut. Dann wird während der Explosion kein Fahrzeug gespawnt und script aufgerufen == mehr performance. 

pull request inc..

**Comment by Ugga-the-Caveman** [comment]
Die wegpunkte des Helis, führen ihren code jetzt nur noch aus wenn der Hubschrauber sich noch bewegen kann.
