### ISSUE TITLE
Kisteninhalt

### ISSUE THREAD

**Issue by Blub0815** [Ugga-the-Caveman/Support#14]
Ich habe gestern und heute versucht auf verschiedenen Weisen die Kiste mit unserem Inhalt zu füllen. ABER es will einfach nicht funktionieren. Entweder habe ich hier zu viel drüber nachgedacht oder ich seh grade vor lauter Wals die Bäume nicht mehr.

Im nachfolgenden findest du den Code dafür 

`_Blubsignalrauch =  "SmokeShellBlue";
_Blubsignallicht =  "Chemlight_blue";

  clearWeaponCargoGlobal this;
  clearMagazineCargoGlobal this;
  clearItemCargoGlobal this;
  clearBackpackCargoGlobal this;

  If (vest player in UGBL_Westen ) then {
      this addBackpackCargo ["BWA3_Kitbag_Tropen_Medic", 2];
        {
          _x addItemCargo ["ACE_packingBandage", 20];
          _x addItemCargo ["ACE_fieldDressing", 10];
          _x addItemCargo ["ACE_quikclot", 35];
          _x addItemCargo ["ACE_elasticBandage", 8];
          _x addItemCargo ["ACE_morphine", 30];
          _x addItemCargo ["ACE_epinephrine", 18];
          _x addItemCargo ["ACE_bloodIV_250", 6];
          _x addItemCargo ["ACE_bloodIV_500", 5];
          _x addItemCargo ["ACE_bloodIV", 5];
        } forEach everyBackpack this;
      }
      else {
        this addBackpackCargo ["BWA3_Kitbag_Fleck_Medic", 2];
          {
              _x addItemCargo ["ACE_packingBandage", 20];
              _x addItemCargo ["ACE_fieldDressing", 10];
              _x addItemCargo ["ACE_quikclot", 35];
              _x addItemCargo ["ACE_elasticBandage", 8];
              _x addItemCargo ["ACE_morphine", 30];
              _x addItemCargo ["ACE_epinephrine", 18];
              _x addItemCargo ["ACE_bloodIV_250", 6];
              _x addItemCargo ["ACE_bloodIV_500", 5];
              _x addItemCargo ["ACE_bloodIV", 5];
        } forEach everyBackpack this;
      };
      this addItemCargoGlobal ["BWA3_30Rnd_556x45_G36_AP",30];
      this addItemCargoGlobal ["ACE_CableTie",10];
      this addItemCargoGlobal ["BWA3_15Rnd_9x19_P8",10];
      this addItemCargoGlobal ["BWA3_10Rnd_762x51_G28_AP",20];
      this addItemCargoGlobal ["hlc_100Rnd_762x51_M_MG3",10];
      this addItemCargoGlobal ["BWA3_200Rnd_556x45",10];
      this addWeaponCargoGlobal ["BWA3_Pzf3_Loaded",4];

      sleep 15;

  BL_Signalrauch = createVehicle [_Blubsignalrauch, position this, [],0,'NONE'];
  BL_Signalrauch attachTo [this, [0,0,0]];

  BL_Signallicht = createVehicle [_Blubsignallicht, position this, [],0,'NONE'];
  BL_Signallicht attachTo [this, [0,0,0]];`

**Comment by Ugga-the-Caveman** [comment]
mal mit hint überprüfen ob der scope wirklich ausgeführt wird und ob die variable this auch auf die kiste verweist.

Hint format["scope wird ausgeführt. this zeigt auf %1 und _this auf %2",this,_this];

**Comment by Blub0815** [comment]
ich habe hier schon mehrere Variablen benutzt

**Comment by Ugga-the-Caveman** [comment]
der Code oben sieht gut aus (vorrausgesetzt this zeigt auf die Supportkiste). der Fehler liegt meiner meinung nach woanders.

welche parameter werden dem script übergeben? bzw wo und wie rufst du es auf?

**Comment by Blub0815** [comment]
habe zuerst mit excVM dann mit Call probiert. Aber irgendwie will es bei mir nicht so. xD

**Comment by Ugga-the-Caveman** [comment]
Ja ne, welche Parameter übergibst du?    ich meine, öhm, ja... (Ugga sprache malfunction)

(parameter) call/spawn/execVM/etc..  _someFunction;

### Konkrete Beispiele:

- call compile preprocessFile "support\init.sqf";  
bereitet text aus datei auf festplatte vor und macht daraus Code, der dann OHNE parameter gecalled wird. 

- [1,vehicle player] call compile preprocessFile "support\createSupport.sqf";
bereitet vor, und called den Code mit dem Array  [1,vehicle player] als parameter.  Inherhalb des Codes stehen die Parameter als Array _this zur verfügung.

- _params call _someCode;
übergibt die Variable _params als parameter und called den schon vorbereitet abgespeicherten code.
Und wieder wird automatisch eine variable _this erstellt, die den gleichen Inhalt hat, wie _params hatte.

...Also das meine ich mit Parameter, das was da vor dem call steht.  =)

**Comment by Blub0815** [comment]
Zuerst habe ich im case 9 das script aufgerufen um zu sehen ob es klappt aber hier ging es nicht. Danach etwas angepasst und im Case mit untergebracht. Dann habe ich einfach mal blabla {}; gemacht und mit call aufgerufen was auch nicht klappte. Jetzt bin ich mir nicht sicher ob ich evtl ne klammer gelöscht hatte da ich eine hinzufügen musste xD

**Comment by Ugga-the-Caveman** [comment]
steht im logfile villeicht was hilfreiches?   C:\Users\Ugga\AppData\Local\Arma 3

Am besten machst du mal nen pull request, damit ich mir das mal in ganz ansehen kann.
das geht am einfachsten, wenn du...

1. im browser https://github.com/Ugga-the-Caveman/Support öffnest
2. dort drückst du auf den knopf Branch:master
3. trag in das textfeld einen namen für die neue branch ein
4. dann drück auf create branch , jetzt ist die neue branch erstellt und geöffnet.  
5. der Knopf Branch: master sagt nun Branch: derNameDeinerBranch
6. jetzt öffne eine Datei die du verändern willst und drücke auf den Stift (Edit this File)
7. Jetzt copy und paste den neuen Inhalt der Datei
8. ganz nach unten scrollen
9. kommentar hinzufügen wenn du willst, und dann auf Commit changes drücken ( Commit directly to the xxx branch. )

jetzt navigiere dich zur nächsten datei, die editiert werden soll und wiederhole schritt 6 bis 9

Wenn  du alle Änderungen durchgeführt hasst, geh wieder auf https://github.com/Ugga-the-Caveman/Support und wähle deine soeben erstellte Branch aus, indem du auf Branch:master drückst und dann den namen deiner Branch anklickst.

Jetzt drück den "New pull request" Button daneben. hier kann man nochmal kommentieren und dem pull request einen Namen geben. Drücke abschliessend auf den grünen Button create Pull request.

**Comment by Ugga-the-Caveman** [comment]
hab hier nochmal was villeicht hilfreiches zu funktionen 
https://community.bistudio.com/wiki/Function
