### ISSUE TITLE
ToDo 

### ISSUE THREAD

**Issue by Blub0815** [Ugga-the-Caveman/Support#16]
**Multiplayer test**
Hier werde ich mal einfach die Karte evtl auf den Server schmeißen
- Multiplayer test [ ] 

**Nicht alle sollen aufrufen**
Habe hier schon eine Lösung die ich noch testen muss aber ich denke GrpFhr und der Funker von Foxtrott reichen als aufrufer.
- Nur bestimmte Personen können aufrufen hinzugefügt [X]

**Comment by Ugga-the-Caveman** [comment]
Vor einem Release, sollten wir diese Dinge noch bearbeiten.

1. Spawnpunkt des Hubschraubers weiter weg. (wie weit?)

2. sicherstellen das der support korrekt unter dem heli gespawnt wird.

3. alle Texte verhübschen.

4. im Singleplayer gründlich prüfen: Funktioniert alles wie gewünscht? werden alle Texte korreckt angezeigt? wie ist die Menüführung/bedienung? kann durch falschbedienung ein Fehler verursacht werden? 

5. Multiplayer Test (allgemeine Funktion schon im singleplayer geprüft, hier vermehrt auf JIP, disconnect und localitäts-Phänomene schauen)

6. Wenn alles so funktioniert wie gewünscht, dann Dokumentation/Tutorial schreiben. was sind die features im überblick? Wie bau ich das in eine map ein? wie passe ich das menü an? usw.

**Comment by Ugga-the-Caveman** [comment]
mach den hier zu, weil wegen aufräumen.
