### ISSUE TITLE
support landet meistens nicht da wo man support hinbestellt hat

### ISSUE THREAD

**Issue by Ugga-the-Caveman** [Ugga-the-Caveman/Support#20]
Weil wegen wind und hubschrauber-speed.

Vielleicht ist das möglich irgendwie auszurechnen wo der support abgeworfen werden muss damit der da landet wo soll.  Ist aber bestimmt aufwendig. 

Lohnt sich das zu untersuchen?   Is das überhaubt ein problem ?

**Comment by Blub0815** [comment]
Ne dann macht das suchen ein wenig spaß und gehört auch dazu. Nachschub landet ja nie 100% an dem ort ^^

**Comment by Blub0815** [comment]
Das kann also gerne so bleiben

**Comment by Ugga-the-Caveman** [comment]
jo kann zu
