### ISSUE TITLE
Spawn Probleme im MP

### ISSUE THREAD

**Issue by Blub0815** [Ugga-the-Caveman/Support#24]
**Also Ugga ich habe mal die aktuelle Version auf den Server geschmissen und getestet.**

> Der Heli Spawn funktioniert wir müssten dann nur die Entfernung erhöhen

**Jetzt das Problem:**
Positiv ist schon mal das er die Fahrzeuge abwirft soweit war ich mit meiner Idee noch nicht.
> Aber sobald der Abwurf gespawnt wird kollidiert der Heli mit der Fracht und es gibt einen riesen Feuerball xD 
Wir  müssen also mal sehen was passiert wenn der Heli unverwundbar ist und ggf gegensteuern

**Comment by Ugga-the-Caveman** [comment]
Die Fracht kollidiert?! die sollte eigentlich weit genug unter dem Heli gespawnt werden.   vielleicht muss die fracht noch etwas tiefer spawnen. 
 Ich werde das prüfen.

**Comment by Ugga-the-Caveman** [comment]
habs grad im Singleplayer getestet.   kann den fehler nicht reproduzieren

**Comment by Blub0815** [comment]
xD Im Singleplayer gehts bei mir auch. Auf dem Server habe ich 3 Supports bestellt und alle drei sind kollidiert xD

**Comment by Blub0815** [comment]
Meine Überlegung wäre es nochmal zu testen wenn die Spawn Entfernung von 300 erhöht wird.

**Comment by Ugga-the-Caveman** [comment]
Mh, die Entfernung _caller - _heliSpawn  sollte keine auswirkung darauf haben.  Aber kann man ruhig mal testen.  

Sehr merkwürdig dass es nur im MP nicht geht. Vielleicht falsche version hochgeladen ?

**Comment by Blub0815** [comment]
Nein so Blöd bin ich nicht xD aber Danke

**Comment by Ugga-the-Caveman** [comment]
Fehler aus der masterbranch entfernt. Dedicated getestet.
