### ISSUE TITLE
Gedanken zu  Fleck oder tropentarn

### ISSUE THREAD

**Issue by Ugga-the-Caveman** [Ugga-the-Caveman/Support#25]
Die bestimmung der Tarnfarbe über die Farbe der Weste des Trägers, gefällt mir nicht so ganz.
Ausserdem habe ich mir Gedanken gemacht, wie man den Zugang zum Support-menü regeln könnte.

Wir haben bisher in keinem Einsatz die Farbe der Uniform gewechselt. Eigentlich steht die benutzte Tarnfarbe also am Anfang der Mission fest und ändert sich im verlauf auch nicht.
 Also warum machen wir nicht einfach eine Globale Variable in der Init. (0=fleck, 1=tropen, 2=whatever)

Oder wir verzichten vollständig darauf, den support in 2 Farben anzubieten. Wir schreiben in die Dokumentation wie man die NachschubOptionen anpassen kann und überlassen den Mapper die Wahl über Fleck oder Tropen

**Comment by Blub0815** [comment]
Mein Problem ist der Mapper. Ich finde die Lösung gut. Sollten die mal wieder auf die Idee kommen die normalen Slotlisten zu verwenden, dann rüsten wir uns an der OCB aus. Neben dem eben beschriebenen Punkt kommt noch Reddog ins Spiel. Er ist für eine eigene Anpassung zu unerfahren und würde dann wieder Ben auf den Sack gehen und das will ich vermeiden.  

Ich bin ja immer für alles offen daher würde ich vorschlagen das du mir dein Ansatz dafür zeigst. ^^ 
Darauf Verzichten möchte ich aber nicht .

**Comment by Ugga-the-Caveman** [comment]
Sehr gute Einwände!  System bleibt erhalten.

Issue closed
