### ISSUE TITLE
Nachschub-menu-acces über RadioBackpack betimmen

### ISSUE THREAD

**Issue by Ugga-the-Caveman** [Ugga-the-Caveman/Support#26]
Hab da ein Paar andere support scripts angeguckt.  In einem bin ich auf folgende Idee gestoßen.

Menü nur anzeigen, wenn man einen Rucksack-Funkgerät trägt.

Dazu müsste man dann so ein Array machen wie ugbl_westen, das könnte auch direkt die funktion davon übernehmen.

**Comment by Blub0815** [comment]
Klingt nicht schlecht damit wäre auch der Funker im Foxtrott Zug mit abgedeckt. Hierfür sollten wir aber ins Template gucken damit wir alle Großen Geräte abdecken.

**Comment by Ugga-the-Caveman** [comment]
Funkrucksack-patch 

Issue closed
